### PR TITLE
Coadd bug and local parameter

### PR DESCRIPTION
**Pull request by profxj**
Fixes a bug introduced in using lists instead of
single object input.

Enables local parameterization and applies it.

Introduces a mininum S/N for std_dev calculation.

Updates to docs, new tests.

### CODE REVIEW

**Comment by profxj** [comment]
@AlexaVillaume -- I got started some of what we had
been discussing.  Check this out before coding your own
bits and pieces on coadding.

**Comment by profxj** [comment]
Have identified and fixed a major bug in our calculation
of the standard deviation.  I would worry that *all* previous
coadds have bad error arrays.

**Comment by AlexaVillaume** [comment]
@profxj - I looked over the changes, looks good to me. Should I merge?

**Comment by profxj** [comment]
Thanks!  Let's let @tiffanyhsyu make a pass too.

**Comment by tiffanyhsyu** [comment]
I'm also happy merging!

**Comment by profxj** [comment]
Merging.

**Pull request merged**
