### PR TITLE
Raw input fix

### PR DESCRIPTION
**Pull request by profxj**
Deals with Python 3 issue on raw_input

Note:  Travis is no longer passing because of
a change to an armed settings file.  Pretty
sure it wasn't me.  :)

### CODE REVIEW

**Comment by rcooke-ast** [comment]
Yes, the settings file is me, and will be fixed with the PR I'll submit when #227 passes :-)

**Comment by rcooke-ast** [comment]
Does this need to be included in armsgs as well?

**Comment by profxj** [comment]
Doesn't appear to be in there.

**Comment by rcooke-ast** [comment]
You're right - sorry! - it's just the pre text that's in armsgs.... merging.

**Pull request merged**
