### PR TITLE
QA with PNGs and HTML

### PR DESCRIPTION
**Pull request by profxj**
Here is an example of what I have in mind.  I launch this
PR for others to review before I continue down this path.

[a few other important, unrelated fixes slipped in, e.g. raw_image]

Please download the tarball here:
https://www.dropbox.com/s/zw8kqe0qikcnx7y/qa.tar.gz?dl=0

and open the HTML file to see what you'd get.

Thus far, I've made the HTML file by hand but I'd have it made
auto-magically.  And there would be separate ones for the exposures.

### CODE REVIEW

**Comment by profxj** [comment]
Have assigned this to a bunch of you as this touches on 
anyone that uses the code.

**Comment by bomilvangjensen** [comment]
I'm not sure I understand the scope of this PR: would the HTML/PNG QA replace the PDF, or be an option (i.e. an alternative to PDF)? The PDF format seems better to me: you can search for the text on the plots, and all information is contained in a single file.
As for the tarball: it only contains a single PNG figure/plot, but maybe that's the intention for this "test"?

**Comment by profxj** [comment]
Yes, it would replace the single PDF approach.  That has been
the source of a number of painful issues..

And, right, the tarball is only a test of what would be created.
Envision one PNG per plot in the current PDFs and one HTML
file per exposure that would contain all the relevant PNGs.

**Comment by bomilvangjensen** [comment]
I would still prefer the PDF, but if you have good reasons to switch to HTML+PNG I would suggest writing the text that is on the PNG plots, e.g. "Trace of the slit edges D01", "S5009", and in other plots maybe "RMS=0.026 (pixels)" or "flex_shift = -2.79862" in the HTML file so that you could search for it. Alternatively, could that information be output to some other file? (or maybe it already is, sorry for my ignorance!)

**Comment by profxj** [comment]
This is a good suggestion.  Let me propose that each exposure/calib setup
have a QA JSON (or YAML) generated with it.  This would also be ingested
into the HTML so you wouldn't have to look at 2 files (but could).

There is such a thing for the extractions (and we should be putting flex_shift
and things like that in there).  It is a Table summarizing all the objects.

**Comment by tiffanyhsyu** [comment]
I'm not hugely opinionated on this--the PDFs were working fine for me, although the number of painful issues others had with PDFs might hit me before long :) All the information that I used from the previous QA PDFs will be here, so I don't have a problem with migrating.

I assume that the naming of the QAs associated with each exposure will have the same naming as before?

**Comment by rcooke-ast** [comment]
If this solution offers a speed-up over the current implementation of pdfs, I'm in favour. The overheads for generating pdfs in the echelle pipeline (at least for the APF with 70 orders) is *far* too long.

My only reservation is the large number of QA files that are going to be generated (especially for the APF pipeline). I think it would be helpful to have a *short* "contents" on every html page, so you can skip to a different page if you're interested in jumping to a particular QA page. Just headings, like "slit trace", "tilts", "tilt PCA", "flexure"  and so forth.

Also, a back and forward button would be helpful to go between the pages without having to open a new html file.

Finally, is it worth keeping in the pdf generation as an option (not by default) for those that might prefer it instead of png/html?

**Comment by profxj** [comment]
I @rcooke-ast 's suggestions for better HTML files and 
will endeavor to make them so.

As for keeping the PDFs, the answer is probably.  
To be clear, here are the issues plaguing me with
the current PDF implementation (some of them
could probably be handled without this major 
shift to PNGs):

- To generate these single PDF files, we have had to open the
file and leave it open while the code runs.  We then add the plots
as we go. 
-  We found some rather slick way to have the PDF close even 
if we crash.  This fails, however, with a segment fault.
-  I was getting bad behaviour when I tried to close a plot, e.g.
use plt.close()
-  Because of the previous bullet, when debugging if one makes
a plot you get a huge number of bogus ones (try it)
-  I've ran out of patience trying to resize figures to look ok 
in the PDF file.  I've already convinced myself that HTML 
will be far easier.
-  These PDF files sometimes get way too large.
-  I've not like how only one of the PDF files gets the Calib QA output
(arcs, flats) and then that QA isn't remade when you start over but
use the MasterFrames.
-  Probably a half-dozen other niggling things..

**Comment by rcooke-ast** [comment]
OK -- these are all good points, and I can already see myself getting annoyed at some of the above issues too. So, while it seemed like a good idea at first, I'm in favour of removing all functionality of generating a single pdf.

Maybe, if we decide to reinclude the pdf option, there might be a way to print the html to a pdf, instead of generating it in real time.... but let's keep that for a future thought...

**Comment by profxj** [comment]
Closing this PR until I have a more polished version.

**Pull request closed without merging**
