### PR TITLE
checking scipy version

### PR DESCRIPTION
**Pull request by adwasser**

### CODE REVIEW

**Comment by rcooke-ast** [comment]
Good job! This looks good to me. Should we also consider adding a check during the PYPIT install (I.e. In setup.py)?

We should definitely check the versions every time PYPIT is run, as you have done - I didn't think about doing that, but it's a good idea!

**Comment by adwasser** [comment]
I put the check in `setup.py` as well.  I'm using the `LooseVersion` instead of `StrictVersion` to handle packages under development like `linetools.__version__ == "0.2.dev974"`, but this might cause issues later on, e.g `LooseVersion("0.2.dev974") < LooseVersion("0.2.1")` returns False.

**Comment by adwasser** [comment]
So the check in `setup.py` seems to break the Travis CI tests.  It works for me, but it seems like `scipy` isn't installed when `setup` runs.

**Comment by profxj** [comment]
Fixed.  Merging.

**Pull request merged**
