### PR TITLE
Fix warning message in arsort

### PR DESCRIPTION
**Pull request by rcooke-ast**
Addresses Issue #213

### CODE REVIEW

**Comment by rcooke-ast** [comment]
@AlexaVillaume: can you please checkout the sortfix branch and run on your data? Please confirm that the warning message disappears and is replaced with an `info` message.

Once this is confirmed, @profxj will review and merge.

**Comment by AlexaVillaume** [comment]
@rcooke-ast: I'm not sure what happened but now I'm getting a bug when I run `pypit_setup`,

```
Traceback (most recent call last):
  File "/Users/alexa/anaconda/bin/pypit_setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alexa/PYPIT/bin/pypit_setup", line 17, in <module>
    setup.main(args)
  File "/Users/alexa/PYPIT/pypit/scripts/setup.py", line 85, in main
    run_pypit.main(pargs)
  File "/Users/alexa/PYPIT/pypit/scripts/run_pypit.py", line 82, in main
    use_masters=args.use_masters, logname=logname, debug=debug)
  File "/Users/alexa/PYPIT/pypit/pypit.py", line 228, in PYPIT
    status = armlsd.ARMLSD(fitsdict)
  File "/Users/alexa/PYPIT/pypit/armlsd.py", line 51, in ARMLSD
    sciexp, setup_dict = armbase.SetupScience(fitsdict)
  File "/Users/alexa/PYPIT/pypit/armbase.py", line 97, in SetupScience
    for idx in settings.spect[key]['index'][sc]:
IndexError: list index out of range
```

I am running  `pypit_setup` on the exact same data that I was when I originally raised the issue. Please advise on what you think might have happened.

**Comment by rcooke-ast** [comment]
@AlexaVillaume: Thanks for this, I had inadvertently skipped over a bunch of code. The new fix should work OK. Could you please confirm?

Thanks!!  (and sorry for the trouble!).

**Comment by AlexaVillaume** [comment]
@rcooke-ast: This looks good! I'm not getting the warning anymore. Thanks so much!

**Comment by rcooke-ast** [comment]
Great - thanks for confirming that this fixes the bug.

@profxj: are you happy to merge?

**Comment by profxj** [comment]
Looks good.  Merging.

**Pull request merged**
