### PR TITLE
Fluxing bug and more

### PR DESCRIPTION
**Pull request by profxj**
Fixes a major bug in Fluxing as noted in Issue #247 

Also processes the standard start and writes to disk.

I am going to request that @tiffanyhsyu generate a fluxing.rst
file to briefly describe this routine (including the flux units!).

No new tests

### CODE REVIEW

**Comment by tiffanyhsyu** [comment]
I've started some fluxing documentation. A few questions:

1) Should I add something on how the sensitivity function is generated and applied? I'm assuming it's a standard procedure, but I'm happy to write a few lines about it.

2) Should we say something about the saved standard star file?

**Comment by profxj** [comment]
Yes, to both (as always more is better).
Thanks!

**Comment by profxj** [comment]
ps.  It is useful to your own work, of course, to understand *very*
well what is being done here.  And by all means, let's discuss anything
that you don't understand.

**Comment by profxj** [comment]
@tiffanyhsyu -- Feel free to merge when you are happy with
what we have here.

**Comment by tiffanyhsyu** [comment]
Ok, I'm stuck on a buggy thing in arflux.py, apply_sensfunc. Right now the code runs, but the standard star's f_lambda doesn't get saved. I'll try to merge this by the end of today.

**Comment by tiffanyhsyu** [comment]
Ok this looks good to me. Merging!

**Pull request merged**
