### PR TITLE
Spectrgraphs folder and code

### PR DESCRIPTION
**Pull request by profxj**
I set out to see if I could handle spectrograph-specific code 
by generating an uber class and then overloading methods, etc.
That failed.

In the end, I've moved all the code that I know is rather instrument
specific to its own spectrographs/ folder.  I suggest the settings
files wind up there someday too.

Also fussed a bit more with the datasec methods.  Improved them
a little.

Am saving the real improvements to the DetectorsPar of @kbwestfall 's
new settings refactor.

Passing all tests except the ones in the Dev-suite that someone broke
recently.  ;)

### CODE REVIEW

**Comment by profxj** [comment]
I should have added that the main gain here is that a Developer
should know to touch all of the files in spectrographs/ when adding
a new instrument.

**Comment by rcooke-ast** [comment]
Although I have no problem with this PR in principle, I would be curious to first know in more detail why the spectrograph class attempt failed. To me, this seems like a really advantageous way to implement this code.

I suppose the benefit of introducing a new folder is that you can organize the code a little better, I think (i.e. group some similar routines together).

I think let's chat about this here in this PR, or on Slack, before we can conclude the best way forward.

**Comment by profxj** [comment]
Indeed, let's discuss here.  

My initial goal was to deal with the various methods we have to load raw data from DEMOS, LRIS
and other instruments.  I thought I might build an Instrument class and then overload a read_raw_data() method in that class.

But I got stuck when I was figuring out how to make this a Parent of ProcessImages or any other class which needs to load raw data.  You obviously can't have variable Parents when defining the class.

On the other hand, it now occurs to me that ProcessImages could instantiate an Instrument object
during its __init__ based on the spectrograph name (or the input file as @jhennawi would prefer).  So that is an option.

But I'm now concerned that this will make it a bit harder to develop than easier.  That is, if one wanted to change the inputs to load_raw or its outputs, you'd have to hunt through each Instrument class as opposed to the one method in io.py.

That said, if you can think of other good uses for an Instrument class, I'm quite open to using it.
I'll add that I have one in mind at the top-level, i.e. for running PYPIT.  More on that to come later ;)

**Comment by jhennawi** [comment]
I think every instrument needs it’s own reader and it’s own default
settings.

These can determined from the header of the first file that gets read in.

Then we can load all the settings and images into a generic class for all
instruments.

The user should then not have to deal with settings at all unless they want
to change from the defaults and this can be done via the pypit file, or by
directly modifying that settings dict.

**Comment by profxj** [comment]
@jhennawi -- This is agreed upon.  The main issue on debate is whether
the code for reading each instrument is bundled into one module (as in this PR)
or separated into separate module/classes.  I've outlined the pros and cons above.

Please weigh in on them.

**Comment by rcooke-ast** [comment]
In my mind, the decision is between: (1) For a given instrument, create a container in a *single* file of all the modifications from a grand set of default functions and settings, versus (2) Grouping algorithms together in a series of files, where each file includes a bunch of case (i.e. if, elif, elif, elif, else) statements. Are these the two options that you are also considering @profxj?

I think I would personally work better with option (1), because if you're developing a single instrument everything is in one file (where we would need to put the default settings anyway). In other words, you know exactly which file to go to (and it's probably already open), in order to make changes from the default. It's also easier to see (for a given instrument) what functions are different from the default functions (this would be an annoying exercise if all of the changes from the defaults are in several files).

In response to your concern @profxj, I had thought of instantiating an Instrument class at the very beginning of the reduction (something that would then be *passed* to ProcessImages etc., not be a parent class, and not be instantiated within ProcessImages), and that this Instrument class instance is a container of all instrument specific settings and functions. So, in `ProcessImages` you would pass a class instance instead of a string for the `spectrograph` keyword. I'm not sure that @jhennawi would agree with this approach, but I feel it would be easy enough to instantiate an instrument class to pass it into something like `ProcessImages`.

As an example of where this would simplify code, in `arprocimg.get_datasec`, you could just call something like 'spect.get_datasec()' instead, where `spect` is the Instrument class defined at the beginning of the reduction. The parent instrument class would have the default (i.e. line 189 of `arprocimg`), and then if an instrument specific change is required the child instrument class would modify this.

My only concern with this approach is that the Instrument Class will become necessarily long.

So, from a code organisation point of view, I think option (1) is cleaner.

**Comment by profxj** [comment]
I'm quite open to either, to be honest.  
But for settings, I am pretty sure those will need
to go in a separate .cfg file.  

So this would make the Class module rather small, in general.

And I'm ok passing objects into objects, but let's see what our
anti-object expert thinks..

And @kbwestfall should weight in too.

**Comment by jhennawi** [comment]
I agree with @rcooke-ast, that having a single container for the instrument to deal with seems preferable, then having everything in one mega-file with if, elif, etc. 

But I'm failing to see how this instrument class is going to be useful once the images are read in. Perhaps we can just discuss what the instrument specific things are for multislit and long slit reductions that go beyond changing parameter values.  

Here is what I can think of: 

1) Reading in images, returning a noise model (i.e. rn_img will depend on amplifier geometry etc.) 

2) Some kind of instrument specific checks on calibration frames, since all the header cards are different. 

3) Running pypit_setup to generate the log, setup files, and .pypit file. 

4) Wavelength calibration, where the individual setups and wave calibration parameters are instrument dependent. 

5) Perhaps something to do with slitless flats for instruments like LRIS. In principle this could be done with a parameter, but maybe there is something I'm overlooking. 

6) Something specific to IR data where for example ABBA images or AB images are created. The reduction steps are often slightly different here, but this could probably be done with a parameter, and an if elif in arms.  This is actually fairly generic to the IR, not specific to any instrument. 

7) In the future maybe something related to instruments like DEIMOS where multiple setups are packed into one reduction. (BLUE/RED). So far this has not been a problem, but I could see that changing. In principle we could simply split it into two instruments and reduce them separately though. 

So I think it is only really 1, 2, 3 and 4. The way I see it, astronomical data is a standard product, but the detectors, how they change with time, how they are arranged, and definitely the headers, are idosyncratic, as well as the grisms/gratings and wavelength setups.  But the reduction tasks are instrument independent once we've figured out how to read the data in and have a noise model and this can usually be dealt with via params. For the wavelengths you need to know the instrument, but again you are using an arc or sky image to do this, and presumably that was read from a file with headers. 

The way I see it, the only place where we really need instrument specific functions is in the process images class which is reading in the images. 

Process images should be able to operate on an image, figure out what instrument it is via header cards, and then decide which instrument reader to call. This seems very straightforward. Whether it is one file per instrument or all readers in one file is a detail. Process images can also figure out from headers whether the frame is supposed to be an arc, flat, etc. and can perform instrument specific header card checks. 

I could be missing something here though since I'm less familiar with the control flow in arms. Please let me know what other instrument specific functions and functionality you think are required. 

Joe

**Comment by profxj** [comment]
I don't see many either.  But I do wish for consensus on the one file (with if, elif etc.)
and many.  I take your vote as ambivalent.  Which gives us:

1 for multiple files
2 for ambivalent

@kbwestfall ?

**Comment by profxj** [comment]
@jhennawi is going to insist that nearly all of our classes be
capable of taking in a file list and file list *only* and then be 
able to proceed.  So I fear the answer to your second question is "no".

Any which way, we are abondoning this approach for that in PR #370 

Closing this PR.

**Pull request closed without merging**
